# Generated by Django 4.1.2 on 2023-01-08 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggerapp', '0002_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=1000)),
            ],
        ),
    ]
